### ISSUE TITLE
Support TypeScript extensions when using `--test` flag.

### ISSUE THREAD

**Issue by remcohaszing** [privatenumber/tsx#257]
### Feature request

Running `node --test` [discovers test files](https://nodejs.org/api/test.html#running-tests-from-the-command-line). However, it doesn’t discover files that end with the `.ts`, `.cts`, `.mts`, or `.tsx` extensions. It would be nice if `tsx` supports this.

### Why?

I would like to leverage the builtin Node test runner. I also like using `tsx`. They work great together, except for this quirk meaning I need to specify all tests as command line parameters.

### Alternatives

The workaround is to specify test files as command line parameters. This works, but it’s not ideal.

### Additional context

https://nodejs.org/api/test.html#test-runner-execution-model

**Comment by privatenumber** [comment]
Happy to accept a PR to add support.

IIRC there isn't an API to extend this. I recommend starting by opening a feature request with Node.js.

**Comment by bestickley** [comment]
My current workaround is: `glob './src/**/*.test.ts' --all --cmd='tsx --test'` which requires an additional dependency: [glob](https://www.npmjs.com/package/glob)

**Comment by kasajian** [comment]
> My current workaround is: `glob './src/**/*.test.ts' --all --cmd='tsx --test'` which requires an additional dependency: [glob](https://www.npmjs.com/package/glob)

This solves the problem even on Windows.

Add this to your scripts section:

        "test": "glob ./test/**/*.test.?s --all --cmd=\"tsx --test\"",

If you don't already have glob as a dependency, add it as a Dev dependency:

        npm i -D glob

**Comment by privatenumber** [comment]
This issue is for implementing a feature, and these workarounds not productive towards that goal so I'm going to hide them.

For anyone encountering this problem:

We're looking for a working approach that actually extends Node.js' `--test` glob.

Personally, I don't use Node's `--test` feature so I'm not incentivized to prioritize this. But I'm happy to prioritize and support anyone that wants to take initiative on this.

**Comment by privatenumber** [comment]
Investigated this.

Seems like the `node --test` flag accepts globs, so you can simply pass in one that catches TypeScript files.

Since everything passed into tsx is passed down to Node, you can also pass it into tsx:
```sh
tsx --test '**/*.test.ts'
```

(Note: quoting the glob prevents your shell from expanding it so Node will expand it instead)

The default glob Node uses is here:
https://github.com/nodejs/node/blob/v21.2.0/lib/internal/test_runner/utils.js#L51

So we can alter that to support TS extensions for the default behavior with TS support:
```sh
tsx --test '**/{test,test/**/*,test-*,*[.-_]test}.?(c|m)@(t|j)s'
```

I plan on intercepting the `--test` flag to use this default instead.

**Comment by remcohaszing** [comment]
Dropped support for Node.js 16 also means [`node:test#run()`](https://nodejs.org/api/test.html#runoptions) can be used.

**Comment by karlhorky** [comment]
Thanks for this issue and #410!

@remcohaszing am I understanding that you are now able to run all Node.js tests like this?

```bash
tsx --test
```
