### ISSUE TITLE
The argument 'methodName' must be a method. Received undefined

### ISSUE THREAD

**Issue by darcyrush** [privatenumber/tsx#400]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

### Problem

Using the native `node:test` library to mock in node 20 seems to cause an error with the `mock` function when using `tsx`. It appears this happens when importing a module using `import * as Object from "./path"` notation

```
$ npm run test-tsx-1

> test-tsx-1
> TSX_TSCONFIG_PATH=./src/tsconfig.json glob 'test/**/*.test.ts' --cmd 'node --import tsx --test'

▶ Main
  ✖ The entry point to the application (1.190797ms)
    TypeError [ERR_INVALID_ARG_VALUE]: The argument 'methodName' must be a method. Received undefined
        at MockTracker.method (node:internal/test_runner/mock/mock:241:13)
        at TestContext.<anonymous> (/home/drush/Workspace/pocs/tsx-methodname-undefined/test/unit/application/main.test.ts:2:1081)
        at Test.runInAsyncScope (node:async_hooks:206:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Test.start (node:internal/test_runner/test:542:17)
        at node:internal/test_runner/test:946:71
        at node:internal/per_context/primordials:488:82
        at new Promise (<anonymous>)
        at new SafePromise (node:internal/per_context/primordials:456:29)
        at node:internal/per_context/primordials:488:9 {
      code: 'ERR_INVALID_ARG_VALUE'
    }

▶ Main (2.768924ms)
```

Conversely `ts-node` can complete all tests 

### Expected behavior

The tests should complete successfully

### Minimal reproduction URL

https://github.com/darcyrush/tsx-methodname-undefined

### Version

4.1.2

### Node.js version

21.2.0

### Package manager

npm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
I've reviewed the reproduction, and it seems a bit complex.

To streamline the investigation, could you consider the following:
- Do you require three tsconfig.json files?
- Is it necessary to have both `test` and `src` directories, or can they be consolidated?
- Are all the files and dependencies essential for reproducing the issue?

As part of my investigation, I would need to closely examine each piece of code and potentially remove some to narrow down the problem. Please trim it down further.

Let me know once you've updated it, and I'll reopen the issue.

**Comment by darcyrush** [comment]
@privatenumber Thank you for taking the time to investigate. You are correct the example was too complex. 

I have eliminated all code unrelated to the problem, including the `tsconfig.json`, although I have a feeling the default configuration is still being taken from somewhere locally. The example repository has been updated.

Hopefully the issue should be much easier to track down now.

**Comment by privatenumber** [comment]
Thanks, I appreciate it.

I dug deeper, and I think your minimal repro can be even smaller. Here's what I simplified to understand the issue better:

```js
// a.js
import { mock } from "node:test";
import * as b from "./b.js";

mock.method(b, "method", () => "mocked");

// b.js
export const method = () => "not mocked";
```

Notes:
- We can ditch TypeScript entirely because it's not relevant to the issue (just ES modules).
- No need for a test runner as it's a runtime error and doesn't require special execution.
- We can get rid of multiple directories for simplicity.

-----

This behavior is actually expected by the ESM spec and not a bug. [Imports are read-only](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), and you're trying to modify the imported object with `mock()`.

You can confirm this yourself by running it in module mode (set `"type": "module"` in `package.json`). You'll get an error: `TypeError: Cannot redefine property: method`.

Trying to directly mutate the imported object through the import-all star also throws an error: `TypeError: Cannot assign to read only property 'method' of object '[object Module]'`.

I hope this helps! Feel free to ask if you have any other questions.
