### ISSUE TITLE
Use ESBuild config

### ISSUE THREAD

**Issue by Henry-Hiles** [privatenumber/tsx#491]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and will not support arbitrary Node.js enhancements
- [X] This request cannot be made to Node.js directly, and is specific to tsx
- [X] I understand this form is not for addressing a bug or seeking help

### Feature request

I would love it if you could add esbuild configuration for TSX to use (specifically plugins). I believe tsx uses esbuild internally, so this should be possible.

### Motivations

Id like to be able to use plugins like `esbuild-plugin-import-pattern` with tsx.

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
tsx is designed to enhance Node with TypeScript support, requiring no configuration to get started.

Even if we wanted to add an esbuild config, we can't because tsx uses esbuild's Transform API to process TypeScript, which doesn't support plugins.

On the flip side, because tsx is built to enhance Node, you can customize it in the same way you would with Node itself. But, if esbuild plugin use is a must for you, using esbuild directly is recommended.

**Comment by Henry-Hiles** [comment]
I see, thank you. I can probably work around it (I just need to figure out how to exclude files in rebuild so they only show up in tax)
