### ISSUE TITLE
Property not assigned to child class when set by parent

### ISSUE THREAD

**Issue by adi518** [privatenumber/tsx#503]
### Acknowledgements

- [X] I searched existing issues to avoid duplicates
- [X] I understand this is a place to report a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative open source project, and relies on community contributions
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/node-5p2jxx?file=index.ts

### Version

v0.0.0

### Node.js version

v18.18.0

### Package manager

npm

### Operating system

macOS

### Problem & expected behavior (under 200 words)

- What happened
Child class instance property `t` was set to `undefined`.
- What I expected
Child class instance property `t` to be set.
- Error stack trace
- Documentation links
- Screenshots

### Contributions

- [ ] I will open a pull request for this issue
- [ ] I will support the work financially (any amount helps)

**Comment by privatenumber** [comment]
Can you make your reproduction minimal? 1 or 2 files if possible.

**Comment by adi518** [comment]
Done. Please check it out now. You have three commands, `start` for JS, `start-tsx`, and `start-ts-node`, so you can compare them.

**Comment by privatenumber** [comment]
This is happening because of [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields).

TypeScript (and ts-node) [sets the target to ES3](https://www.typescriptlang.org/tsconfig#target) by default, which yields this behavior. But tsx sets the target based on your runtime version.

Read more about it here: https://esbuild.github.io/content-types/#no-type-system
